name: Django Github Action

on:
  push:
    branches:
      - main
  pull_request:
    pull_request:
      types:
        - synchronize
        - opened
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint the code
        run: |
          flake8 . --extend-exclude=dist,build,static,migrations,env,venv --ignore=E501,F811

      - name: Run Unit test cases
        run: |
          python manage.py test
          
